---
title: "Introduction"
author: "Koen Lucas"
date: "`r Sys.Date()`"
output: html_document
bibliography: references.bib
---

```{=html}
<style>
body {
text-align: justify}
</style>
```
```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}

library(knitr)
library(formatR)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()


colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }
```

# Introduction

It has often been argued that scientific achievement exhibits a ‘Matthew effect’, meaning that previous success is an indication of later success, furthering the increase in distinction [@bol2018]. First introduced by Merton (1968), the ‘Matthew effect’ can therefore be seen as a self-reinforcing mechanism turning past success into future success. For instance, if only one of two equally talented young scholars authored a successful publication, this scholar is predicted to have a more successful career. To clarify, a successful scholar can often accumulate more ‘credit’ over time than unknown researchers, even if their work is of similar quality. This mechanism, often synonymously called cumulative advantage [@barabasi2002; @perc2010], is consequently causing inequality in the success of academics as it basically comes down to ‘winner takes all’ [@diprete2006]. As argued by Merton (1968), scientific contribution is more visible for a community when introduced by high-ranking scientist. Thus, when early success is a predictor for future success, inequality between these scholars continues to grow.

The ‘Matthew effect’ is often explained through preferential attachment. In the case of co-authorship this means that those who were successful before are a preferential collaboration partner to those without those early successes. As a result, previously successful scholars attract more opportunities for more success in the future while unsuccessful scholars attract less resources, decreasing their chances of becoming successful in the future. We can thus presume that collaboration networks hold a preference to connect with those who are already well-connected. Hence, it can expected that highly visible/already established researchers have more opportunities of co-authorship [@hancean2016]. Consequently, it can be argued that scholars who have higher prestige, have an increased network size compared to scholars with less prestige.

This is in line with the idea that collaboration networks exhibit a scale-free network. The structure of such networks is characterised by a power-law distribution, where a few nodes dominate the network, creating hubs (ref.). If that is the case, this would mean that collaboration networks in science would be centered around those scholars with the highest amount of prestige, this way illustrating a 'Matthew effect'. For this reason, I propose the following research question:

1.  *To what extent are collaboration networks in Dutch sociology departments centered around scholars with high prestige?*

Furthermore, 'Matthew effects' in science have been found in multiple aspects of the scientific domain such as institutional prestige [@medoff2006], funding [@bol2018], and citations [@wang2014]. Additionally, preferential attachment mechanisms in the growth of collaboration networks has been found in previous research [@barabasi2002; @perc2010], however evidence concerning preferential attachment as the driving mechanism of co-authorship is mixed [@ferligoj2015]. Furthermore, little is known about the implications of the ‘Matthew effect’ in creating co-authorship ties considering the prestige of a scholar rather than only looking at the role of already existing co-authorship ties. This way it is possible to disentangle whether it is the existing collaboration network or the ego-focused prestige of a scientist that shapes co-authorship ties in future collaboration networks. Ergo, this study will look into this phenomenon by focusing on how the prestige (e.g. h-index) and the number of co-authorship ties of a scientist at one point accumulates into more co-authorship ties on a later timepoint. I therefore propose the following two research questions:

2.  *To what extent does an author’s number of co-authorship ties at T1 impact the increase in co- authorship ties at T2?*
3.  *To what extent does an author’s citation score at T1 impact the increase in in co-authorship ties at T2?*

## References
