---
title: "Results - RSiena"
author: "Koen Lucas"
date: "`r Sys.Date()`"
output: html_document
---

# Results - RSiena

```{=html}
<style>
body {
text-align: justify}
</style>
```
```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}

library(knitr)
library(formatR)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=FALSE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()


colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
```

```{r clean workspace, include = FALSE}

rm(list = ls())

```

```{r load functions, include=FALSE}
rm(list = ls())


fpackage.check <- function(packages) {
    lapply(packages, FUN = function(x) {
        if (!require(x, character.only = TRUE)) {
            install.packages(x, dependencies = TRUE)
            library(x, character.only = TRUE)
        }
    })
}

fsave <- function(x, file = NULL, location = "./data/processed/") {
    ifelse(!dir.exists("data"), dir.create("data"), FALSE)
    ifelse(!dir.exists("data/processed"), dir.create("data/processed"), FALSE)
    if (is.null(file))
        file = deparse(substitute(x))
    datename <- substr(gsub("[:-]", "", Sys.time()), 1, 8)
    totalname <- paste(location, file, "_", datename, ".rda", sep = "")
    save(x, file = totalname)  #need to fix if file is reloaded as input name, not as x. 
}

fload <- function(filename) {
    load(filename)
    get(ls()[ls() != "filename"])
}

fshowdf <- function(x, ...) {
    knitr::kable(x, digits = 2, "html", ...) %>%
        kableExtra::kable_styling(bootstrap_options = c("striped", "hover")) %>%
        kableExtra::scroll_box(width = "100%", height = "300px")
}


```


```{r load packages, include=FALSE}

packages <- c("tidyverse", 
              "scholar", 
              "RSiena", 
              "RsienaTwoStep", 
              "igraph")

fpackage.check(packages)
```


```{r load data, include=FALSE}

fulldata <- fload("./Data/full_data.Rdata")

df_ego <- fload("./Data/df_ego.Rdata")
  
df_works <- fload("./Data/df_works.Rdata")

```


```{r step 1 define data, include=FALSE}

df_nets <- fulldata$nets

length(df_nets)
dim(df_nets)[1]

wave1 <- df_nets[1,,]
wave2 <- df_nets[2,,]

# put diagonal to zero
diag(wave1) <- 0
diag(wave2) <- 0

# binary ties
wave1[wave1 > 1] <- 1
wave2[wave2 > 2] <- 1

# put networks in array --> right format for Rsiena
net_soc_array <- array(data = c(wave1, wave2), dim = c(dim(wave1), 2))
dim(net_soc_array)

```


```{r variables, include=FALSE}

net <- sienaDependent(net_soc_array)

career_age <- as.numeric(df_ego$career_age)
career_age <- coCovar(career_age)


h_index <- as.numeric(df_ego$h_index)
h_index <- coCovar(h_index)

data_siena <- sienaDataCreate(net, career_age, h_index)

```


```{r step 2 create effect structure, include=FALSE}

myeff <- getEffects(data_siena)

```


```{r step 3 initial description, include=FALSE}

print01Report(data_siena, modelname = "./results/first_model")

```

## Model 1
```{r specify model1 only networkstructures, include=FALSE}

myeff1 <- getEffects(data_siena)

myeff1 <- includeEffects(myeff1, isolateNet) # to control for isolates
myeff1 <- includeEffects(myeff1, inPop) # nodes are attracted to nodes with more indegrees
myeff1 <- includeEffects(myeff1, outAct) # control for more active nodes outdegrees                      
myeff1 <- includeEffects(myeff1, inAct) # control for behaviour of nodes with more indegrees
myeff1 <- includeEffects(myeff1, transTrip) # controls for triadic relationships
myeff1 <- includeEffects(myeff1, recip) # control for reciprocity

```

```{r estimate model1, echo=FALSE}

myAlgorithm1 <- sienaAlgorithmCreate(projname = "first_model")
ansM1 <- siena07(myAlgorithm1, data = data_siena, effects = myeff1, returnDeps = TRUE)

ansM1

```

## Model 2
```{r specify model2 with ego effects, include=FALSE}

myeff2 <- getEffects(data_siena)

myeff2 <- includeEffects(myeff2, isolateNet) # to control for isolates
myeff2 <- includeEffects(myeff2, inPop) # nodes are attracted to nodes with more indegrees
myeff2 <- includeEffects(myeff2, outAct) # control for more active nodes outdegrees                      
myeff2 <- includeEffects(myeff2, inAct) # control for behaviour of nodes with more indegrees
myeff2 <- includeEffects(myeff2, transTrip) # controls for triadic relationships
myeff2 <- includeEffects(myeff2, recip) # control for reciprocity


myeff2 <- includeEffects(myeff2, altX, interaction1 = "h_index") # absolute difference to h_index
myeff2 <- includeEffects(myeff2, egoX, interaction1 = "career_age") # ego's are more likely receive ties from younger scholars
myeff2 <- includeEffects(myeff2, altX, interaction1 = "career_age") # ego's are more likely to send ties to older scholars

```


```{r estimate model2, echo=FALSE}

myAlgorithm2 <- sienaAlgorithmCreate(projname = "second_model")
ansM2 <- siena07(myAlgorithm2, data = data_siena, effects = myeff2, returnDeps = TRUE)

ansM2

```



```{r} 

```

