---
title: "First model"
author: "Koen Lucas"
date: "2024-10-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load functions, include=FALSE}
rm(list = ls())


fpackage.check <- function(packages) {
    lapply(packages, FUN = function(x) {
        if (!require(x, character.only = TRUE)) {
            install.packages(x, dependencies = TRUE)
            library(x, character.only = TRUE)
        }
    })
}

fsave <- function(x, file = NULL, location = "./data/processed/") {
    ifelse(!dir.exists("data"), dir.create("data"), FALSE)
    ifelse(!dir.exists("data/processed"), dir.create("data/processed"), FALSE)
    if (is.null(file))
        file = deparse(substitute(x))
    datename <- substr(gsub("[:-]", "", Sys.time()), 1, 8)
    totalname <- paste(location, file, "_", datename, ".rda", sep = "")
    save(x, file = totalname)  #need to fix if file is reloaded as input name, not as x. 
}

fload <- function(filename) {
    load(filename)
    get(ls()[ls() != "filename"])
}

fshowdf <- function(x, ...) {
    knitr::kable(x, digits = 2, "html", ...) %>%
        kableExtra::kable_styling(bootstrap_options = c("striped", "hover")) %>%
        kableExtra::scroll_box(width = "100%", height = "300px")
}


```


```{r load packages, include=FALSE}

packages <- c("tidyverse", 
              "scholar", 
              "RSiena", 
              "RsienaTwoStep", 
              "igraph")
fpackage.check(packages)

```


```{r load data, include=FALSE}

fulldata <- fload("./Data/full_data.Rdata")

df_ego <- fload("./Data/df_ego.Rdata")
  
df_works <- fload("./Data/df_works.Rdata")

```


# Step 1: define data
```{r create right structure }

df_nets <- fulldata$nets

length(df_nets)
dim(df_nets)[1]

wave1 <- df_nets[1,,]
wave2 <- df_nets[2,,]

# put diagonal to zero
diag(wave1) <- 0
diag(wave2) <- 0

# binary ties
wave1[wave1 > 1] <- 1
wave2[wave2 > 2] <- 1

# put networks in array --> right format for Rsiena
net_soc_array <- array(data = c(wave1, wave2), dim = c(dim(wave1), 2))
dim(net_soc_array)

```
```{r dependent variable}

net <- sienaDependent(net_soc_array)

```


```{r independent variable}

career_age <- as.numeric(df_ego$career_age)
career_age <- coCovar(career_age)


h_index <- as.numeric(df_ego$h_index)
h_index <- coCovar(h_index)

```

```{r create siena data object}

data_siena <- sienaDataCreate(net, career_age, h_index)

```


# step 2: create effects structure
```{r create effects structure}

myeff <- getEffects(data_siena)
effectsDocumentation((myeff))

```

# step 3: get initial description
```{r initial description}

print01Report(data_siena, modelname = "./results/first_model")

```

# step 4: specify model
```{r include effects}

myeff <- includeEffects(myeff, isolateNet, inPop, outAct, inAct, degPlus)

myeff <- includeEffects(myeff, altX, interaction1 = "h_index")
myeff <- includeEffects(myeff, egoX, altX, interaction1 = "career_age")

```

# step 5: estimate model
```{r estimate model}

myAlgorithm <- sienaAlgorithmCreate(projname = "first_model")
ansM1 <- siena07(myAlgorithm, data = data_siena, effects = myeff, returnDeps = TRUE)

ansM1

```

