---
title: "Week 6 - new models"
author: "Koen Lucas"
date: "2024-10-09"
output: html_document
---

```{=html}
<style>
body {
text-align: justify}
</style>
```
```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}

library(knitr)
library(formatR)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()


colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
```

```{r clean workspace, include = FALSE}

rm(list = ls())

```

```{r load functions, include=FALSE}
rm(list = ls())


fpackage.check <- function(packages) {
    lapply(packages, FUN = function(x) {
        if (!require(x, character.only = TRUE)) {
            install.packages(x, dependencies = TRUE)
            library(x, character.only = TRUE)
        }
    })
}

fsave <- function(x, file = NULL, location = "./data/processed/") {
    ifelse(!dir.exists("data"), dir.create("data"), FALSE)
    ifelse(!dir.exists("data/processed"), dir.create("data/processed"), FALSE)
    if (is.null(file))
        file = deparse(substitute(x))
    datename <- substr(gsub("[:-]", "", Sys.time()), 1, 8)
    totalname <- paste(location, file, "_", datename, ".rda", sep = "")
    save(x, file = totalname)  #need to fix if file is reloaded as input name, not as x. 
}

fload <- function(filename) {
    load(filename)
    get(ls()[ls() != "filename"])
}

fshowdf <- function(x, ...) {
    knitr::kable(x, digits = 2, "html", ...) %>%
        kableExtra::kable_styling(bootstrap_options = c("striped", "hover")) %>%
        kableExtra::scroll_box(width = "100%", height = "300px")
}


```


```{r load packages, include=FALSE}

packages <- c("tidyverse", 
              "scholar", 
              "RSiena", 
              "RsienaTwoStep", 
              "igraph")

fpackage.check(packages)
```


```{r load data, include=FALSE}

fulldata <- fload("./Data/full_data.Rdata")

df_ego <- fload("./Data/df_ego.Rdata")
  
df_works <- fload("./Data/df_works.Rdata")

```


# Step 1: define data
```{r create right structure }

df_nets <- fulldata$nets

length(df_nets)
dim(df_nets)[1]

wave1 <- df_nets[1,,]
wave2 <- df_nets[2,,]

# put diagonal to zero
diag(wave1) <- 0
diag(wave2) <- 0

# binary ties
wave1[wave1 > 1] <- 1
wave2[wave2 > 2] <- 1

# put networks in array --> right format for Rsiena
net_soc_array <- array(data = c(wave1, wave2), dim = c(dim(wave1), 2))
dim(net_soc_array)

```
```{r dependent variable}

net <- sienaDependent(net_soc_array)

```


```{r independent variable}

career_age <- as.numeric(df_ego$career_age)
career_age <- coCovar(career_age)


h_index_cat <- as.numeric(df_ego$h_index_cat)
h_index_cat <- coCovar(h_index_cat)

```

```{r create siena data object}

data_siena <- sienaDataCreate(net, career_age, h_index_cat)

```


# step 2: create effects structure
```{r create effects structure}

myeff <- getEffects(data_siena)
effectsDocumentation((myeff))

```

# step 3: get initial description
```{r initial description}

print01Report(data_siena, modelname = "./results/first_model")

```

# step 4: specify model
```{r include effects}

myeff <- getEffects(data_siena)

# myeff <- includeEffects(myeff, isolateNet, inPop, outAct, inAct, transTrip)

# myeff <- includeEffects(myeff, altX, interaction1 = "h_index_cat")
# myeff <- includeEffects(myeff, egoX, altX, interaction1 = "career_age")


myeff <- includeEffects(myeff, inPop, recip)

```

# step 5: estimate model
```{r estimate model}

myAlgorithm <- sienaAlgorithmCreate(projname = "first_model")
ansM1 <- siena07(myAlgorithm, data = data_siena, effects = myeff, returnDeps = TRUE)

ansM1

```

```{r functions sienaGOF}
# see here: ?'sienaGOF-auxiliary'

# The geodesic distribution is not available from within RSiena, and therefore is copied from the
# help page of sienaGOF-auxiliary:

# GeodesicDistribution calculates the distribution of non-directed geodesic distances; see
# ?sna::geodist The default for \code{levls} reflects the usual phenomenon that geodesic distances
# larger than 5 do not differ appreciably with respect to interpretation.  Note that the levels of
# the result are named; these names are used in the \code{plot} method.
GeodesicDistribution <- function(i, data, sims, period, groupName, varName, levls = c(1:5, Inf), cumulative = TRUE,
    ...) {
    x <- networkExtraction(i, data, sims, period, groupName, varName)
    require(sna)
    a <- sna::geodist(symmetrize(x))$gdist
    if (cumulative) {
        gdi <- sapply(levls, function(i) {
            sum(a <= i)
        })
    } else {
        gdi <- sapply(levls, function(i) {
            sum(a == i)
        })
    }
    names(gdi) <- as.character(levls)
    gdi
}

# The following function is taken from the help page for sienaTest

testall <- function(ans) {
    for (i in which(ans$test)) {
        sct <- score.Test(ans, i)
        cat(ans$requestedEffects$effectName[i], "\n")
        print(sct)
    }
    invisible(score.Test(ans))
}
```


```{r test GOF}

gofi0 <- sienaGOF(ansM1, IndegreeDistribution, verbose = FALSE, join = TRUE, varName = "net")
gofo0 <- sienaGOF(ansM1, OutdegreeDistribution, verbose = FALSE, join = TRUE, levls = c(0:10, 15, 20),
    varName = "net")
gof0.gd <- sienaGOF(ansM1, GeodesicDistribution, cumulative = FALSE, verbose = FALSE, join = TRUE, varName = "net")


```


```{r}

plot(gofi0, main = "")
```


```{r}
plot(gofo0, main = "")
```

```{r}
plot(gof0.gd, main = "")

```

